### ISSUE TITLE
Fix broken image links

### ISSUE THREAD

**Issue by oeway** [BiaPyX/BiaPy-bioimage-io#5]
Hi, could you please fix the broken links in the collection.yaml file?

For example:
 * https://raw.githubusercontent.com/danifranco/BiaPy-bioimage-io/main/images/2d_self-supervised.png
 * https://raw.githubusercontent.com/danifranco/BiaPy-bioimage-io/main/images/3d_classification.png
 * ...
 
 These images makes the website looks broken at the moment:
<img width="1552" alt="Screen Shot 2023-12-05 at 11 09 51 AM" src="https://github.com/danifranco/BiaPy-bioimage-io/assets/478667/53c88a2f-5180-4e71-805b-28e9e84caaff">

**Comment by danifranco** [comment]
We have corrected the paths, now they should be visible! Once the page is updated will double check if there is still something wrong.

**Comment by oeway** [comment]
Thanks! It looks like there are still some links missing, for example: https://raw.githubusercontent.com/danifranco/BiaPy-bioimage-io/main/images/3d_semantic_segmentation.png

Could you please check all of them make sure them all exists? You can see them [here](https://bioimage.io/#/?type=application).

**Comment by danifranco** [comment]
All the links exist, the one you are linking is not anymore in the [collection.yaml](https://github.com/danifranco/BiaPy-bioimage-io/blob/main/collection.yaml) file. Just checked again and all images are visible:

![image](https://github.com/danifranco/BiaPy-bioimage-io/assets/32868330/3e5e9d5f-2c22-484c-a213-824f14ec953a)

**Comment by oeway** [comment]
Awesome! Thanks!
