### ISSUE TITLE
Validation check not passed in last commit 

### ISSUE THREAD

**Issue by danifranco** [BiaPyX/BiaPy-bioimage-io#7]
Hello @FynnBe ,

My last commit did not pass the validation check. I just took a look to the [validation file in ilastik](https://github.com/ilastik/bioimage-io-resources/blob/main/.github/workflows/validate_ilastik_collection.yaml) to see if there was any difference with mine and saw little detail: `actions/checkout@v2` to `actions/checkout@v4`. Do I need to change this? Sorry for the silly question :S , I'm not very familiar with this...

Thank you so much!

**Comment by FynnBe** [comment]
Hi @danifranco 

the partner resource repos are being deprecated. 
All resources should be uploaded just like outside contributers do (I tried to move all partner resources to the new backend, so no need for further action if all resources you had in this collection are there already).

I'll update the ilastik collection accordingly...

**Comment by FynnBe** [comment]
As this repo is not used to develop any BioEngine apps; and with moving all BiaPy models and notebooks to regular bioimage.io uploads this repo might not be needed at all for now.

**Comment by danifranco** [comment]
Great! Thank you Fynn!

**Comment by danifranco** [comment]
One thing @FynnBe : can you please point me where I need to add the new notebooks made and added in the last commit of this repo? Just so I have it clear for future additions and to not bother again with this.

**Comment by FynnBe** [comment]
no bother at all!
currently bioimage.io uploads go via https://bioimageio-uploader.netlify.app/#/uploader/add
Write to me in the chat if you want to setup programmatic upload, which is available to members of the bioimage-io GH organization.
